# 베이스 이미지 설정
FROM openjdk:17-jdk-slim

# 작업 디렉토리 설정
WORKDIR /app

# Gradle 빌드 결과물 복사
COPY mohaji-0.0.1-SNAPSHOT.jar /app/mohaji-0.0.1-SNAPSHOT.jar

# 로그 파일을 위한 디렉토리 생성 및 권한 설정
RUN mkdir -p /app/logs && chmod -R 777 /app/logs

# 포트 설정
EXPOSE 8412

# 애플리케이션 실행
ENTRYPOINT ["sh", "-c", "java -jar /app/mohaji-0.0.1-SNAPSHOT.jar > /app/logs/mohaji.log 2>&1"]
