version: '3'
services:
  db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mohaji
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8412:8412"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/mohaji"
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - web_data:/app
      - /home/ubuntu/mohaji.log:/app/logs/mohaji.log
    # 디버깅을 위해 사용
    # command: ["tail", "-f", "/dev/null"]
volumes:
  db_data: {}
  web_data: {}
