name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew clean build

    - name: List build/libs directory
      run: ls -la build/libs

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/libs/mohaji-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: build/libs/

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}"
        chmod 600 ~/.ssh/id_rsa

    - name: Add known hosts
      run: |
        touch ~/.ssh/known_hosts
        ssh-keyscan -H 13.125.216.111 >> ~/.ssh/known_hosts

    - name: Copy files via SSH
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa build/libs/mohaji-0.0.1-SNAPSHOT.jar ubuntu@13.125.216.111:/home/ubuntu/
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa mohaji_docker/dockerfile ubuntu@13.125.216.111:/home/ubuntu/
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa mohaji_docker/docker-compose.yml ubuntu@13.125.216.111:/home/ubuntu/
    - name: Deploy Docker image
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@13.125.216.111 << 'EOF'
          cd /home/ubuntu/

          # MySQL 컨테이너를 중지하고 제거
          docker stop mysql || true
          docker rm mysql || true

          # 기존 리소스를 정리하고 Docker Compose 실행
          docker-compose down
          docker-compose up -d --build
          
        EOF
