name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

# Gradle 실행권한 부여
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew clean build

#디버깅용
    - name: List build/libs directory
      run: ls -la build/libs

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

    - name: Copy files via SSH
      run: |
        scp -o StrictHostKeyChecking=no -i ${{ secrets.AWS_SSH_PRIVATE_KEY }} build/libs/*.jar ec2-user@54.180.249.224:/home/ec2-user/
        scp -o StrictHostKeyChecking=no -i ${{ secrets.AWS_SSH_PRIVATE_KEY }} Dockerfile ec2-user@54.180.249.224:/home/ec2-user/
        scp -o StrictHostKeyChecking=no -i ${{ secrets.AWS_SSH_PRIVATE_KEY }} docker-compose.yml ec2-user@54.180.249.224:/home/ec2-user/

    - name: Deploy Docker image
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_SSH_PRIVATE_KEY }} ec2-user@your-ec2-instance-public-ip << 'EOF'
          cd /home/ec2-user/
          docker-compose down
          docker-compose up -d --build
        EOF
