name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    # Gradle 실행권한 부여
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew clean build

    # 디버깅용
    - name: List build/libs directory
      run: ls -la build/libs

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        echo "Setting up SSH key..."
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "SSH key setup completed."

    - name: Add known hosts
      run: |
        echo "Adding known hosts..."
        touch ~/.ssh/known_hosts
        ssh-keyscan -H 54.180.249.224 >> ~/.ssh/known_hosts
        echo "Known hosts added."

    - name: Copy files via SSH
      run: |
        echo "Copying files via SSH..."
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa build/libs/*.jar ubuntu@54.180.249.224:/home/ubuntu/
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa Dockerfile ubuntu@54.180.249.224:/home/ubuntu/
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa docker-compose.yml ubuntu@54.180.249.224:/home/ubuntu/
        echo "Files copied."

    - name: Deploy Docker image
      run: |
        echo "Deploying Docker image..."
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@54.180.249.224 << 'EOF'
          cd /home/ubuntu/
          docker-compose down
          docker-compose up -d --build
          echo "Docker image deployed."
        EOF
        echo "Deployment completed."

